In [2]:
import pandas as pd

In [3]:
# i have a csv file wiht columns sample_id and price
df = pd.read_csv('submission.csv')
display(df.head())

   sample_id      price
0     100179   8.936327
1     245611  12.523448
2     146263  23.011330
3      95658   4.139470
4      36806  20.795368

In [5]:
import numpy as np

# round to 3 decimals
df['price'] = df['price'].round(3)

# use boolean masks on the index to apply ceiling/floor every 10 rows
mask_ceil = df.index % 10 == 0
mask_floor = df.index % 10 == 5

df.loc[mask_ceil, 'price'] = np.ceil(df.loc[mask_ceil, 'price'])
df.loc[mask_floor, 'price'] = np.floor(df.loc[mask_floor, 'price'])

display(df.head(20))

    sample_id   price
0      100179   9.000
1      245611  12.523
2      146263  23.011
3       95658   4.139
4       36806  20.795
5      148239   4.000
6       92659  22.180
7        3780  13.162
8      196940  42.406
9       20472   9.552
10     121721  19.000
11     127336   4.048
12      20801  45.019
13      30103   9.689
14      68691  20.047
15     230703   9.000
16       3342  38.295
17     115635  17.737
18     221565  10.996
19     265927  11.618

In [6]:
# save
df.to_csv('submission_rounded.csv', index=False)